on:
  push:
    tags:
      - "*"
    branches:
      - "chore/update-actions"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Publish package to hex.pm
        uses: erlangpack/github-action@v3
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
