name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, release/** ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Set up Elixir
      uses: erlef/setup-beam@v1.15.4
      with:
        version-file: .tool-versions
        version-type: strict

    - name: Set mix.lock file hash environment variable
      run: echo "MIX_LOCK_HASH=${{ hashFiles('**/mix.lock') }}" >> $GITHUB_ENV
      shell: bash

    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-deps-${{ env.MIX_LOCK_HASH }}
        restore-keys: ${{ runner.os }}-mix-

    - name: Install dependencies
      run: mix deps.get

    - name: Restore build artifacts
      uses: actions/cache@v2
      with:
        path: _build
        key: ${{ runner.os }}-build-${{ env.MIX_LOCK_HASH }}
        restore-keys: ${{ runner.os }}-build-

    - name: Check formatting
      run:  mix format --check-formatted

    - name: Run tests
      run: mix test

    - name: Restore dialyzer PLTS
      uses: actions/cache@v2
      with:
        path: priv/plts
        key: ${{ runner.os }}-plts-${{ env.MIX_LOCK_HASH }}
        restore-keys: ${{ runner.os }}-plts-

    - name: Run dialyzer
      run: mix dialyzer
